[project]
name = "ocrpdf-gui"
version = "0.1.0"
description = "Tkinter GUI for ocrmypdf"
authors = [{name="Your Name", email="you@example.com"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ocrmypdf",
]

[project.scripts]
ocr-gui = "ocr_gui:main"

